

import { SiteConfig } from './types';
import { SERVICES } from './lib/servicesData.mjs';

// Logo updated as requested.
const GENERATED_LOGO_URL = 'https://i.ibb.co/DP0khScL/image.png';

export const INITIAL_CONFIG: SiteConfig = {
  companyInfo: {
    name: '느티울',
    logo: GENERATED_LOGO_URL,
    slogan: 'A FRESH AND PEACEFUL HAVEN',
    description: '상담부터 청소까지 대표가 직접\n관리하는 신뢰받는 기업.\n\n고객님의 공간에\n평화와 휴식을 선물합니다.',
    phone: '010-4880-7386',
    email: 'danger3662@naver.com',
    address: '군포시 도마교동 463 1층',
    blog: 'https://blog.naver.com/kslee0143',
    blog2: 'https://blog.naver.com/decline11731',
  },
  themeColor: '#34D399',
  services: SERVICES,
  portfolio: [
    {
      id: 'p0',
      title: '지식산업센터 데코타일 박리 및 광택 복원',
      category: '바닥 청소',
      beforeImage: 'https://i.ibb.co/zT9kzgXM/0.jpg', // Dirty floor
      afterImage: 'https://i.ibb.co/W4VNZrNt/0-1.jpg', // Shiny floor
      description: '오랫동안 관리되지 않아 검게 찌든 바닥을 정밀 박리하여 본연의 색상과 광택을 되찾아드렸습니다.',
      date: '2024. 02. 15',
    },
    {
      id: 'p1',
      title: '물류 창고 바닥 복원',
      category: '바닥 왁스 코팅',
      beforeImage: 'https://i.ibb.co/4ZnR5V1P/0.jpg', // Dull Floor
      afterImage: 'https://i.ibb.co/PzhSqbKy/0-1.jpg', // Reflective Floor
      description: '바닥 세척 후 프리미엄 왁스 2회 코팅으로 내구성과 심미성을 동시에 확보했습니다.',
      date: '2024. 01. 20',
    },
    {
      id: 'p2',
      title: '신축 아파트 준공 후 입주 정밀 청소',
      category: '입주 청소',
      beforeImage: 'https://i.ibb.co/DgCkK5sH/0.jpg', // Messy Room
      afterImage: 'https://i.ibb.co/RGMHdqHg/0-1.jpg', // Clean Empty Room
      description: '공사 먼지와 건축 잔여물을 완벽 제거하고 친환경 살균 소독을 완료했습니다.',
      date: '2023. 12. 10',
    },
    {
      id: 'p3',
      title: '사무실 부분 공사로 인한 먼지 케어',
      category: '사무실 청소',
      beforeImage: 'https://i.ibb.co/jkcxxMvX/0.jpg', // Messy Office
      afterImage: 'https://i.ibb.co/XZNpXstj/0-1.jpg', // Clean Office
      description: '직원들의 쾌적한 업무 환경을 위해 바닥 왁싱과 유리 파티션, 개인 책상 먼지 제거를 진행했습니다.',
      date: '2023. 11. 05',
    },
    {
      id: 'p4',
      title: '프랜차이즈 식당 주방 후드/바닥 청소',
      category: '식당 청소',
      beforeImage: 'https://i.ibb.co/P81m9xh/0.jpg', // Busy/Messy Kitchen
      afterImage: 'https://i.ibb.co/qMK02dz1/0-1.jpg', // Clean Kitchen
      description: '공사로 인해 먼지가 가득한 주방 후드와 미끄러운 바닥을 고온 스팀으로 완벽하게 세척했습니다.',
      date: '2023. 10. 25',
    },
    {
      id: 'p5',
      title: '공장 바닥 기계 세척 및 분진 제거',
      category: '공장 청소',
      beforeImage: 'https://i.ibb.co/mW50Br7/0.jpg', // Industrial Dirty
      afterImage: 'https://i.ibb.co/Pvhtf03p/0-1.jpg', // Clean Warehouse
      description: '공장 가동 중 발생한 묵은 분진과 바닥의 지게차 타이어 자국을 전문 장비로 제거했습니다.',
      date: '2023. 10. 12',
    },
    {
      id: 'p6',
      title: '화재 현장 그을음 제거 및 복구',
      category: '화재 청소',
      beforeImage: 'https://i.ibb.co/kLTyGMb/0.jpg', // Burnt/Mess
      afterImage: 'https://i.ibb.co/Lzcp8wgT/0-1.jpg', // Clean Wall/Room
      description: '화재로 인한 천장과 벽면의 그을음을 제거하고 냄새 제거 시공을 완료했습니다.',
      date: '2023. 09. 30',
    },
    {
      id: 'p7',
      title: '배관이 터져 물 난리난 쓰레기집',
      category: '특수 청소',
      beforeImage: 'https://i.ibb.co/G4n4Y85n/0.jpg',
      afterImage: 'https://i.ibb.co/YBxzcsBx/0-1.png',
      description: '오랫동안 방치된 생활 폐기물 5톤을 처리하고 악취 제거 및 소독을 진행했습니다.',
      date: '2023. 09. 15',
    },
    {
      id: 'p8',
      title: '쿠우쿠우 인테리어 공사 후 분진 제거 및 마감 청소',
      category: '인테리어 청소',
      beforeImage: 'https://i.ibb.co/bjbGcGxQ/0.jpg',
      afterImage: 'https://i.ibb.co/TJJFSJ3/0-1.jpg',
      description: '인테리어 공사 후 남은 미세 분진과 건축 자재 냄새를 제거하여 즉시 입주 가능한 상태로 만들었습니다.',
      date: '2024. 03. 18',
    },
    {
      id: 'p9',
      title: '인천 남동공단 배수관 역류로 인한 침수 청소',
      category: '침수 청소',
      beforeImage: 'https://i.ibb.co/9HW3K1W9/0-1.jpg',
      afterImage: 'https://i.ibb.co/KcSDLjw1/0.jpg',
      description: '긴급 출동하여 배수 작업을 진행하고, 오염된 가구 폐기 및 실내 건조, 살균 작업을 완료했습니다.',
      date: '2024. 04. 05',
    },
    {
      id: 'p10',
      title: '사무실 이전 후 원상복구 및 바닥 청소',
      category: '사무실 청소',
      beforeImage: 'https://i.ibb.co/DfxFCV0r/1.jpg',
      afterImage: 'https://i.ibb.co/3yvWRR7P/1-1.jpg',
      description: '계약 만료로 인한 사무실 원상복구 작업. 바닥에 먼지 자국과 본드, 찌든 때를 완벽히 제거하여 보증금 반환에 문제없도록 만들었습니다.',
      date: '2024. 05. 10',
    },
    {
      id: 'p11',
      title: '커플링 공방 미세먼지 제거',
      category: '신축 준공청소',
      beforeImage: 'https://i.ibb.co/4Zf0D8K8/0.jpg',
      afterImage: 'https://i.ibb.co/G4nYWGvV/0-1.jpg',
      description: '보이지 않는 공사 분진과 유해물질을 제거하는 정밀 청소. 쾌적한 환경을 조성했습니다.',
      date: '2024. 06. 02',
    },
    {
      id: 'p12',
      title: '교회 도끼다시 바닥 본드제거',
      category: '바닥 청소',
      beforeImage: 'https://i.ibb.co/gMQ31KSM/1.jpg',
      afterImage: 'https://i.ibb.co/4R2MxszB/1-1.jpg',
      description: '도끼다시 바닥 위에 오랫동안 묵어있던 본드를 제거했습니다.',
      date: '2024. 04. 15',
    },
    {
      id: 'p13',
      title: '상가 도끼다시 바닥 위 오염 제거',
      category: '바닥 청소',
      beforeImage: 'https://i.ibb.co/3YdCVbXq/2.jpg',
      afterImage: 'https://i.ibb.co/HTdCNSCC/2-1.jpg',
      description: '오랜시간 바닥에 붙어있던 본드와 오염을 제거하였습니다.',
      date: '2024. 03. 22',
    },
    {
      id: 'p14',
      title: '학원 데코타일 바닥 왁스 코팅',
      category: '바닥 왁스 코팅',
      beforeImage: 'https://i.ibb.co/HfgWzCs3/1.jpg',
      afterImage: 'https://i.ibb.co/5XP6LSBf/1-1.jpg',
      description: '학생들이 생활하는 공간인 만큼 내구성이 강한 친환경 왁스를 사용하여 안전하고 깔끔한 환경을 조성했습니다.',
      date: '2024. 02. 28',
    },
    {
      id: 'p15',
      title: '사무실 바닥 2회 왁스 코팅',
      category: '바닥 왁스 코팅',
      beforeImage: 'https://i.ibb.co/d4RP1J8F/2.jpg',
      afterImage: 'https://i.ibb.co/M5Pt6yT1/2-1.jpg',
      description: '바닥 세척 후 프리미엄 왁스 2회 코팅으로 스크래치를 방지하고, 고급스러운 광택으로 사무실 분위기를 개선했습니다.',
      date: '2024. 01. 15',
    },
    {
      id: 'p16',
      title: '빌라 리모델링 후 입주 청소',
      category: '입주 청소',
      beforeImage: 'https://i.ibb.co/mrL4Nntg/1.jpg',
      afterImage: 'https://i.ibb.co/ch1b2nL4/1-1.jpg',
      description: '리모델링 공사 후 발생한 미세 분진과 유해 물질을 제거하여 건강한 주거 환경을 마련했습니다.',
      date: '2023. 11. 25',
    },
    {
      id: 'p17',
      title: '아파트 인테리어 후 청소',
      category: '입주 청소',
      beforeImage: 'https://i.ibb.co/JwsCbHKz/2.jpg',
      afterImage: 'https://i.ibb.co/XZNKfZLx/2-1.jpg',
      description: '신축 아파트의 공사 잔여물을 제거하고, 모든 서랍과 붙박이장 내부까지 꼼꼼하게 청소하여 상쾌한 새 출발을 도왔습니다.',
      date: '2023. 10. 18',
    },
    {
      id: 'p18',
      title: '고깃집 주방 후드 및 덕트 기름때 제거',
      category: '식당 청소',
      beforeImage: 'https://i.ibb.co/39zhJp9F/1.jpg',
      afterImage: 'https://i.ibb.co/zc2QDMF/1-1.jpg',
      description: '화재 위험이 높은 후드와 덕트 내부의 기름때를 전문 약품과 고온 스팀으로 완벽하게 제거하여 안전한 주방 환경을 만들었습니다.',
      date: '2024. 05. 20',
    },
    {
      id: 'p19',
      title: '후드 기름 필터에 낀 기름때 제거',
      category: '식당 청소',
      beforeImage: 'https://i.ibb.co/FbgFkVgF/2.jpg',
      afterImage: 'https://i.ibb.co/q392NNvH/2-1.jpg',
      description: '후드 필터들을 전부 해제하여 기름때를 벗겨냈습니다.',
      date: '2024. 04. 11',
    },
    {
      id: 'p20',
      title: '지게차가 다니던 바닥 오염들 제거',
      category: '공장 청소',
      beforeImage: 'https://i.ibb.co/s9B1gtt3/1.jpg',
      afterImage: 'https://i.ibb.co/F4MXqScc/1-1.jpg',
      description: '바닥에 테이프 자국, 바퀴 자국을 제거하여 깨끗한 내부환경을 조성했습니다.',
      date: '2023. 09. 05',
    },
    {
      id: 'p21',
      title: '식품 공장 바닥 및 생산 라인 세척',
      category: '공장 청소',
      beforeImage: 'https://i.ibb.co/rfFktmg3/2.jpg',
      afterImage: 'https://i.ibb.co/5X6xFBtc/2-1.jpg',
      description: 'HACCP 기준에 맞춰 인체에 무해한 약품으로 생산 라인과 바닥의 오염을 제거하여 위생적인 생산 환경을 조성했습니다.',
      date: '2023. 08. 19',
    },
    {
      id: 'p22',
      title: '전소된 건물의 엉겨붙은 자재들은 제거하는 작업',
      category: '화재 청소',
      beforeImage: 'https://i.ibb.co/pj9pFcL0/0.jpg',
      afterImage: 'https://i.ibb.co/ywK8k8C/0-1.png',
      description: '특수 약품으로 가구와 바닥의 그을음을 제거하고, 오존 시공으로 유독성 냄새를 완벽히 분해했습니다.',
      date: '2023. 07. 28',
    },
    {
      id: 'p23',
      title: '아랫층 화재로 인한 그을음으로 인한 청소',
      category: '화재 청소',
      beforeImage: 'https://i.ibb.co/tTBRJjR4/1.jpg',
      afterImage: 'https://i.ibb.co/TD9GnZbX/1-1.jpg',
      description: '복도에 화재 폐기물을 안전하게 처리하고, 그을음을 제거를 진행했습니다.',
      date: '2023. 06. 10',
    },
    {
      id: 'p24',
      title: '방 한칸에 쓰레기를 모아놓은 집',
      category: '특수 청소',
      beforeImage: 'https://i.ibb.co/xS8SGsMv/1.jpg',
      afterImage: 'https://i.ibb.co/FkxjDZ9r/1-1.jpg',
      description: '고객님의 마음을 위로하고 앞의로의 새로운 시작을 위한 청소를 진행했습니다.',
      date: '2024. 03. 10',
    },
    {
      id: 'p25',
      title: '직장 생활로 인해 관리를 못한 집',
      category: '특수 청소',
      beforeImage: 'https://i.ibb.co/tPLrQ4Gj/2.jpg',
      afterImage: 'https://i.ibb.co/LD9MnL1h/2-1.jpg',
      description: '장기간 방 한쪽에 방치된 쓰레기를 처리하고, 깊게 밴 냄새와 세균을 특수 장비로 완벽하게 제거했습니다.',
      date: '2024. 01. 29',
    },
    {
      id: 'p26',
      title: '에버랜드 캔디샾 내부 공사 후 청소',
      category: '인테리어 청소',
      beforeImage: 'https://i.ibb.co/3Ycc0C2B/1.jpg',
      afterImage: 'https://i.ibb.co/M5SxHD2p/1-1.jpg',
      description: '인테리어로 인해 생긴 분진과 시멘트 가루를 완벽하게 제거하여 최상의 오픈 컨디션을 만들었습니다..',
      date: '2023. 12. 20',
    },
    {
      id: 'p27',
      title: '카페 인테리어 공사 후 청소',
      category: '인테리어 청소',
      beforeImage: 'https://i.ibb.co/LhSzCrd1/2.jpg',
      afterImage: 'https://i.ibb.co/JjjJNDX4/2-1.jpg',
      description: '오픈 일정에 차질이 없도록 신속하게 공사 분진과 폐기물을 처리하고, 유리창과 집기를 맑고 깨끗하게 닦아냈습니다.',
      date: '2023. 11. 11',
    },
    {
      id: 'p28',
      title: '지하 주차장 침수 후 배수 및 청소',
      category: '침수 청소',
      beforeImage: 'https://i.ibb.co/Df7rgHgs/1.jpg',
      afterImage: 'https://i.ibb.co/gbrJKK7C/1-1.jpg',
      description: '대형 양수기로 신속하게 배수 작업을 진행하고, 바닥의 토사와 오염물을 제거한 뒤 소독을 완료했습니다.',
      date: '2023. 08. 01',
    },
    {
      id: 'p29',
      title: '주택 싱크대 역류 청소',
      category: '침수 청소',
      beforeImage: 'https://i.ibb.co/DfcMJPs0/2.jpg',
      afterImage: 'https://i.ibb.co/JFwrw0LH/2-1.jpg',
      description: '싱크대 역류로 인해 생긴 오물을 제거 후 청소진행 그리고 소독으로 마무리.',
      date: '2023. 07. 15',
    },
    {
      id: 'p30',
      title: '청담 BAR 준공 청소',
      category: '신축 준공청소',
      beforeImage: 'https://i.ibb.co/gLf4zG3G/1.jpg',
      afterImage: 'https://i.ibb.co/20w0sxt1/1-1.jpg',
      description: '최고급 마감재를 보호하며 미세 분진과 시멘트 가루를 완벽하게 제거하여 최상의 입주 컨디션을 만들었습니다.',
      date: '2023. 05. 12',
    },
    {
      id: 'p31',
      title: '만두전골전문점 신축 공사 후 전체 준공 청소',
      category: '신축 준공청소',
      beforeImage: 'https://i.ibb.co/m5ZwjDg2/2.jpg',
      afterImage: 'https://i.ibb.co/MDKr2F7N/2-1.jpg',
      description: '건물 내부의 공사 잔여물, 페인트 자국, 본드 자국 등을 제거하고 외벽 유리까지 깨끗하게 마감했습니다.',
      date: '2023. 04. 20',
    },
    {
      id: 'p32',
      title: '사무실 집기 및 바닥 청소',
      category: '사무실 청소',
      beforeImage: 'https://i.ibb.co/gMKV6hzz/2.jpg',
      afterImage: 'https://i.ibb.co/qYVdtnLF/2-1.jpg',
      description: '정기적인 관리로 쾌적한 환경, 상쾌한 업무 공간을 제공하여 업무 효율을 높였습니다.',
      date: '2023. 03. 25',
    },
    {
      id: 'p33',
      title: '베란다에 담배를 쌓아둔 집',
      category: '특수 청소',
      beforeImage: 'https://i.ibb.co/nNmFsS0M/3.jpg',
      afterImage: 'https://i.ibb.co/8nqTzwMk/3-1.jpg',
      description: '고객 맞춤형 비대면 원상 복구 작업과 악취 제거 및 멸균 피톤치드 공간 소독을 완료했습니다.',
      date: '2024. 04. 18',
    },
    {
      id: 'p34',
      title: '화재 연기가 넘어와서 생긴 바닥 그을음',
      category: '화재 청소',
      beforeImage: 'https://i.ibb.co/DPFgbt6D/2.jpg',
      afterImage: 'https://i.ibb.co/ksJVRjF2/2-1.jpg',
      description: '실내에 밴 매캐한 연기 냄새와 타르 잔존물을 오존 살균 정화 및 전문 약품 시공으로 완전히 소독 탈취했습니다.',
      date: '2023. 09. 12',
    },
    {
      id: 'p35',
      title: '화재로 생긴 천장 그을음 제거 작업',
      category: '화재 청소',
      beforeImage: 'https://i.ibb.co/60GnBynq/3.jpg',
      afterImage: 'https://i.ibb.co/Gv4sqpJB/3-1.jpg',
      description: '연소 유해 물질을 고온 스팀과 중화제로 완벽 세정하여 안심하고 리모델링할 수 있도록 복원했습니다.',
      date: '2023. 10. 05',
    },
    {
      id: 'p36',
      title: '침수 현장 오수 악취 제거 및 살균 소독',
      category: '침수 청소',
      beforeImage: 'https://i.ibb.co/Pz3VRHYt/3.jpg',
      afterImage: 'https://i.ibb.co/k2F0Bq75/3-1.jpg',
      description: '침수 부산물로 인한 악취와 세균을 초미립자 살균 소독과 피톤치드로 말끔하게 정화 처리했습니다.',
      date: '2023. 11. 08',
    },
    {
      id: 'p37',
      title: '지식산업센터 복합판넬 외벽 찌든 물때 고압 세척',
      category: '외벽 청소',
      beforeImage: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=1000&auto=format&fit=crop&q=80',
      afterImage: 'https://i.ibb.co/9mvGmZ71/image.jpg',
      description: '비바람과 매연으로 얼룩진 건물 복합판넬을 전용 약품 도포 후 고압 세척하여 본래의 선명하고 깨끗한 외관을 되찾았습니다.',
      date: '2024. 05. 28',
    },
    {
      id: 'p38',
      title: '상가 사옥 빌딩 대형 유리창 및 석재 외벽 정밀 세정',
      category: '외벽 청소',
      beforeImage: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=1000&auto=format&fit=crop&q=80',
      afterImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1000&auto=format&fit=crop&q=80',
      description: '유리창 유막과 석재 백화 현상을 안전하게 제거하고 발수 마감하여 맑고 투명한 시야와 쾌적한 건물 외관을 완성했습니다.',
      date: '2024. 06. 15',
    }
  ],
};